global:
  scrape_interval: 5s

scrape_configs:
  - job_name: dcapal-backend
    metrics_path: "/"
    static_configs:
      - targets: ['host.docker.internal:9000']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']