version: "3.9"
services:
  redis:
    image: redis/redis-stack-server
    container_name: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - dcapalnetwork
    volumes:
      - ./config/redis/redis-stack.conf:/redis-stack.conf
      - ./data/redis/:/data
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 10s
      timeout: 10s
      retries: 3

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - 8010:8080
    networks:
      - dcapalnetwork
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


networks:
  dcapalnetwork: