[package]
name = "dcapal-optimizer-wasm"
version = "0.1.0"
authors = ["Leonardo Arcari <leonardo1.arcari@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
# WASM dependencies
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }
js-sys = "0"
console_error_panic_hook = { version = "0.1.6", optional = true }
# Library dependencies
minilp = "0"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0"
wasm-bindgen-futures = "0.4.32"
futures = "0.3.23"
anyhow = "1.0.62"
lazy_static = "1.4.0"
rand = "0.8.5"
getrandom = { version = "0.2.7", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
