name: DcaPal Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version
    
    - name: Lint
      run: |
        cd dcapal-backend
        cargo fmt -- --check
        cargo clippy -- -D warnings

    - name: Build and Test
      run: |
        cd dcapal-backend
        cargo test
