name: DcaPal Frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  optimizer-build-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    
    - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version
    
    - name: Lint
      run: |
        cd dcapal-optimizer-wasm
        cargo fmt -- --check
        cargo clippy -- -D warnings
 
    - name: Test
      run: |
        cd dcapal-optimizer-wasm
        cargo test
        wasm-pack test --headless --chrome
        wasm-pack test --headless --firefox
        
    - name: Build
      run: |
        cd dcapal-optimizer-wasm
        wasm-pack build
        
    - name: Archive dcapal-optimizer-wasm pkg
        uses: actions/upload-artifact@v3
        with:
          name: dcapal-optimizer-wasm-pkg
          path: dcapal-optimizer-wasm/pkg
